### ISSUE TITLE
How am I supposed to know the searchWindowName in a Spanish Windows version (or other languages)?

### ISSUE THREAD

**Issue by vieira-temes** [Illustar0/PowerToysRunEnhance#1]
When I press the Windows key on Windows 11 to start searching (that's Windows Search), I can't see the name of the "window" (no actual window opens, just the search interface). I tried a few common Spanish words to search, to no avail.

**Comment by Illustar0** [comment]
~~Although I'm not sure, the value of searchWindowName might be "Search" in Spanish?~~

You can use Inspect.exe or WinSpy (which can be a little difficult to operate) or something else, and check the window of the search to see the Name.(I'm pondering if there's any way to automate this)
If you're using Inspect.exe, make sure you're looking at the search window itself (e.g. the black boxed location in the picture is the correct one)
![QQ20241114-0012221](https://github.com/user-attachments/assets/84a12907-e10e-4519-b1db-f3449729c878)

**Comment by Fefedu973** [comment]
This is not working for me unfortunately
The name is null (i clicked on the top of the window where you put the clack box)
![image](https://github.com/user-attachments/assets/4ffaa7c9-0e80-4cb8-b3ed-617435b65190)

**Comment by Illustar0** [comment]
This is so weird, can you tell me what language you are using? I switched the language to Spanish (Spain) and managed to get searchWindowsName=Buscar.
There's good news, I've figured out how to automate this process (
Stay tuned!

**Comment by Fefedu973** [comment]
The language is set to french!

**Comment by Illustar0** [comment]
> The language is set to french!

Oddly enough, I was unable to reproduce the problem. Maybe it's a Microsoft issue?
Using the language French (France) I get searchWindowsName=Rechercher
![QQ20241115-233939](https://github.com/user-attachments/assets/49ab68b6-e19c-4584-ad64-451b87a2c9ce)

**Comment by Fefedu973** [comment]
When I put "Rechercher" it doesn't work however  when I put this in an auto hotkey script that I made it worked, strange

**Comment by Fefedu973** [comment]
i have been able to make it work by updating my windows

**Comment by Illustar0** [comment]
Very good
