### ISSUE TITLE
Show a dialog to confirm config file has been read

### ISSUE THREAD

**Issue by vieira-temes** [Illustar0/PowerToysRunEnhance#2]
There should be some dialog popping up after running the executable, confirming the config file has been read and the parameters updated.

**Comment by Illustar0** [comment]
Good idea. I'll do it tomorrow. Maybe put it in the tray icon?

**Comment by vieira-temes** [comment]
If it's running in the background, it could stay in the tray icon, yes.

**Comment by Illustar0** [comment]
Try [v0.0.4](https://github.com/Illustar0/PowerToysRunEnhance/releases/tag/v0.0.4) ?
All known bugs have been fixed (probably)

**Comment by Illustar0** [comment]
The v0.0.4 file has been re-uploaded, and the tray icon now works properly
