### ISSUE TITLE
Windows Security sees PowerToysRunEnhance as a Trojan virus

### ISSUE THREAD

**Issue by e10withadot** [Illustar0/PowerToysRunEnhance#3]
![image](https://github.com/user-attachments/assets/f330cf5e-07dc-427a-8fd3-62abe93c6742)

pretty self explanatory apart from this image

**Comment by Illustar0** [comment]
I think this is a common false positive, which often happens on exe packaged from Python source code. If you are still worried, you can compile it yourself from source code

**Comment by c8p0** [comment]
I checked the code and its indeed completely squeecky clean! Thanks @Illustar0  for making this open source - I also like your other projects. Maybe it would be a potential "chore" to switch to another compiler.

Someone on redit mentioned: . 

"For example, by removing the multiprocessing module (it makes sense to remove it if you don't use it in your project)," -> reduces the probability of being flagged as trojan.

**Comment by Illustar0** [comment]
> I checked the code and its indeed completely squeecky clean! Thanks [@Illustar0](https://github.com/Illustar0) for making this open source - I also like your other projects. Maybe it would be a potential "chore" to switch to another compiler.
> 
> Someone on redit mentioned: .
> 
> "For example, by removing the multiprocessing module (it makes sense to remove it if you don't use it in your project)," -> reduces the probability of being flagged as trojan.

Actually, I have a plan to rewrite the entire project using C#. But I have too much on my plate right now, so I don't have a specific date for it  :)
